### ISSUE TITLE
nested arrays

### ISSUE THREAD

**Issue by thesrinivas** [zserge/jsmn#103]
Does this lib handle nested arrays:
myObj = {
    "name":"John",
    "age":30,
    "cars": [
        { "name":"Ford", "models":[ "Fiesta", "Focus", "Mustang" ] },
        { "name":"BMW", "models":[ "320", "X3", "X5" ] },
        { "name":"Fiat", "models":[ "500", "Panda" ] }
    ]
 }

**Comment by lopter** [comment]
Yes.
