### ISSUE TITLE
Integrate LICENSE into jsmn.c to make it easier to integrate in other projects

### ISSUE THREAD

**Issue by thomask77** [zserge/jsmn#109]
Hi!

I just found jsmn, and would like to use it in my project. Could you please integrate the LICENSE directly into jsmn.c?

This would also enable the library to be listed in this popular list of single-file c libraries:
    https://github.com/nothings/single_file_libs#json

best regards,
thomas!

**Comment by pt300** [comment]
It's a thing now.
