### ISSUE TITLE
Error when dynamically allocating number of tokens

### ISSUE THREAD

**Issue by tmarrinan** [zserge/jsmn#113]
I am receiving an error when dynamically allocating the number of tokens.

```
char *message = "{\"msg\":\"hello\",\"data\":\"world!\"}";
int len = strlen(message);
int max_tokens = jsmn_parse(&parser, message, len, NULL, 0); // returns 5
jsmntok_t *tokens = (jsmntok_t*)malloc(max_tokens * sizeof(tokens));
int num_tokens = jsmn_parse(&parser, message, len, tokens, max_tokens); // returns 0?!?!
```

This seems to be an issue with calling `jsmn_parse` twice on the same string. If I remove line 3 and replace `max_tokens` with `5` elsewhere, then it works.

**Comment by zserge** [comment]
On the first run the parser worked fine up to the very end of your input string. Thus, on the second run the same parser says it's all done. Try doing `jsmn_init` to reset the parser before the second run.

**Comment by tmarrinan** [comment]
Ok, Thanks. So I just need to re-initialize before each parse.
