### ISSUE TITLE
ifdef in struct definition

### ISSUE THREAD

**Issue by kjhermans** [zserge/jsmn#145]
If you have an #ifdef in your structure definitions, the size of your structure, as perceived by the compiler, may vary, depending on whether the user is compiling the .c file themselves or not / have the #define on or off in different Makefiles. I suggest to take away the #ifdef JSMN_PARENT_LINKS in the jsmntok_t.

**Comment by kjhermans** [comment]
But you malloc() those things, right? the jsmntok_t's, I mean.

**Comment by pt300** [comment]
Allocate them yourself, yes.

**Comment by kjhermans** [comment]
Ok. I suppose I'll just have to stick with forcibly defining the macro in the header file itself, as a patch.

**Comment by pt300** [comment]
Now as the library is just a .h file it's not a problem anymore
