### ISSUE TITLE
question: how to best split parser into multiple specialized ones

### ISSUE THREAD

**Issue by ghost** [zserge/jsmn#150]
please appologise if this is a "stupid" question... I am new to jsmn and so far I have only found simple examples on how to use it. I try to build a parser which is "assembled" from multiple specialized parsers.

For a data structure like this (always arrives as this big chunk of data) I like to split the parser into a **house_parser()** and **car_parser()**.

``` json
{
"house": {"architecture": "wood_frame", "sqm": 100, ...},
"car": {"brand": "", "horsepower": 40} 
}
```

I hope you can share some pointers on how to achieve this. Just a pointer to a sample or codebase which is doing this would be great!
Thank you.

**Comment by ghost** [comment]
@pt300 thank you for this code. Your code implements one big parser which regretably is exactly what I try to avoid. Instead of using a monolithic parser I am looking for a way to decompose into simpler sub-parsers. In other words I try to build a parser which is "assembled" / composed from multiple specialized parsers.

**Comment by pt300** [comment]
It's possible to split the parsing of house and car into separate parsing functions, but you still will need a parser for the root object which will call these "subparsers" when it encounters the appropriate keys.
I could try writing something like that if you still need it.

**Comment by ghost** [comment]
right, it is possible. I hope smb. will share how they usually go about it. you know, a JSON file usually gets pretty big (often with hundreds or even thousands of elements) - I am still convinced that a suitable parser would not be engineed as a monolith. Unless the parser code is automatically generated from - lets say json-schema - which I think would be ok, too.
