### ISSUE TITLE
issues with there being no jsmn.c

### ISSUE THREAD

**Issue by sparky4** [zserge/jsmn#153]
src/lib/jsmn/jsmn.h(456): Warning! W202: Symbol 'jsmn_init' has been defined, but not referenced
src/lib/jsmn/jsmn.h(265): Warning! W202: Symbol 'jsmn_parse' has been defined, but not referenced

this is with #define JSMN_STATIC in 16_map.h

it is for https://github.com/sparky4/16/

**Comment by pt300** [comment]
JSMN is now a header only library. That means the jsmn.c file doesn't exist and to use jsmn only the jsmn.h file needs to be included.

**Comment by sparky4** [comment]
it seems to be causing warnings with compiling for the game i am working on.
the compiler is open watcom 2.0

**Comment by pt300** [comment]
I see no issue. You just provided some warnings about jsmn symbols being defined but not referenced.

**Comment by sparky4** [comment]
the compiler is confused i think

**Comment by pt300** [comment]
There's not enough information about this problem nor it seems like a problem with jsmn itself. Are you able to provide something more specific?

**Comment by sparky4** [comment]
oooh when the jsmn.h is called by another c header file it gives the warnings. so jsmn.h must be called by the .c file that uses it. ah

**Comment by sparky4** [comment]
If you include the jsmn.h file in the C file it is needed in it will not spew warnings.
