### ISSUE TITLE
JSMN_ERROR_NOMEM issue: multiple layers of JSON structure

### ISSUE THREAD

**Issue by Kuan-ChiehHsu** [zserge/jsmn#155]
Does jsmn support parsing multiple layers of JSON structure?
When I try a 880KB .json file, it fails.

**Comment by pt300** [comment]
Just make sure you allocate large enough array of tokens

**Comment by pt300** [comment]
If you mean something like multiple objects at root then it's not really well handled as far as I know. Will change in the future tho.
