### ISSUE TITLE
[Bug] JSMN does no find the token of a valid JSON string

### ISSUE THREAD

**Issue by ngreve** [zserge/jsmn#165]
When using a JSON string like `{"input":22}`, JSMN does not find the token with its value, even though it's a valid JSON String. JSMN needs spaces around the integer value like `{"input": 22 }`. The first string, without spaces, should work too.

**Comment by pt300** [comment]
I am unable to reproduce this

**Comment by the-mush** [comment]
do you have a way to check if JSMN is getting an ASCII space character (value 32 in decimal)? Maybe it's getting a UNICODE encoded space character and I think it only works with ASCII (which would convert the space character into multiple characters, something like `U0020b`).
