### ISSUE TITLE
fatal bug

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [zserge/jsmn#173]
i couldnt even started using it... when i found the worst bug of al...

THERES FUCKING CODE ON A .H

fix it IMEDIATELLY please... that is totally unaceptable

**Comment by pt300** [comment]
That was a choice made some time ago. You can read more in #149 and the README. If you have constructive criticism of that decision you are more than welcome to share it with everyone.

**Comment by MyTDT-Mysoft** [comment]
no i will go back to breah gasoline, while putting melon juice on my car, while finish my catalog of all the types of air that i'm selling...

**Comment by MyTDT-Mysoft** [comment]
its very retarded you name standards that it can be compiled when you broke the rule #1 no code on .h.. they are .headers not .code, so if you will do stupid things then why even bother naming it .h? name it library.jsmn directly... since you made the extension be meaningless...

**Comment by pt300** [comment]
So doing it the way it has been done here is wrong just because, despite the problems it actually helped solve?
