### ISSUE TITLE
Last value is not properly read

### ISSUE THREAD

**Issue by ghost** [zserge/jsmn#176]
I tried the following string:
{"Header":{"Magic":3405655469,"Code":2,"Length":24},"Bar":0,"Offset":12288,"Data":4660}

For some reason, the value of "Data" is 4 and not 4660. 
This happens only in the last token. 

Thank you.

**Comment by pt300** [comment]
Mind sharing more informations about your setup? I was not able to reproduce the problem with the data you provided.

**Comment by ghost** [comment]
Sorry. My mistake. 
Works fine.
