### ISSUE TITLE
strip backslashes?

### ISSUE THREAD

**Issue by paxter** [zserge/jsmn#189]
Should backslashes in strings be stripped? I noticed that backslashes are used to escape the `"` within strings and jsmn keeps them.
I'm not sure whether jsmn should handle such cases or the overlaying software. So I started this issue.

Thanks in advance and thanks for this great project. :)

**Comment by pt300** [comment]
As of now JSMN does not unescape JSON strings, so it has to be done manually. In the future this might be an optional feature of JSMN tho.
For more informations refer to [Strings section of RFC-8259](https://tools.ietf.org/html/rfc8259#page-8).

**Comment by paxter** [comment]
Ah, good to know that. Thanks for your fast reply and the hint with the RFC.
