### ISSUE TITLE
compiling for arm help

### ISSUE THREAD

**Issue by Yossefosman** [zserge/jsmn#200]
I am trying to compile an image for a router with identical hardware to tplink-archer-c5-v2 or linksys-ea6200 and i can't find any instructions i tried a couple of times but no luck Thanks for the help

**Comment by pt300** [comment]
Could you explain what exactly have you tried and what kind of issues you ran into?

**Comment by Yossefosman** [comment]
it was my mistake

**Comment by Yossefosman** [comment]
thanks for the reply

**Comment by Yossefosman** [comment]
submitted to the wrong repo sorry
