### ISSUE TITLE
Default "example/simple.c" not working

### ISSUE THREAD

**Issue by mihir-chauhan** [zserge/jsmn#208]
Hey! I was trying this out and what I did is used the `examples/simple.c` program and then just added the `jsmn.h` to the directory. When it runs, it prints out:

```
- User: ERROR*s
- Admin: ERROR*s
- UID: ERROR*s
- Groups:
  * ERROR*s
  * ERROR*s
  * ERROR*s
  * ERROR*s
```

Is there anything I am doing wrong? Thank you.

**Comment by mihir-chauhan** [comment]
By the way, at the top, I do: `#include "jsmn.h"`

**Comment by pt300** [comment]
It seems like a problem with libc on your system not supporting the "%.*s" in printf. That means it's an issue with printing in the example, not JSMN itself.

**Comment by mihir-chauhan** [comment]
Yes, I spent some time and found the solution. Thank you!
