### ISSUE TITLE
UnEven JSON object

### ISSUE THREAD

**Issue by embbo** [zserge/jsmn#210]
hi i am working with JSON simple example, which works fine , but problem is what happens if I have uneven values for example 
{
{ "A":"1", "B":"2", "C":"3"},
 { "A":"1", "B":"2"} ,
{ "A":"1", "B":"2", "C":"3", "D":"4"},
}
I can get values but after finishing each iteration , I have to call funtion ,  how can i call function after each itteration  I am using simple example.

**Comment by pt300** [comment]
I am sorry, I cannot understand your issue. You have to provide better description of what are you doing, what is it you expect and what happens instead.

**Comment by ddgflorida** [comment]
Your example is not valid JSON. Did you mean [ ... ] ? Plus you have an extra comma.
