### ISSUE TITLE
not able to parse json data if one of the key is same as another key's value

### ISSUE THREAD

**Issue by pramodnitmz** [zserge/jsmn#212]
Test Input i.e config.json content :  {"ver":"01","elem_cnt":2,"1":"connect","2":"connect1234"}
here key "2" is the same as elem_cnt's value

Output: 
01
2
connect
1

Expected Output:
01
2
connect
connect1234

**Comment by pt300** [comment]
I am not really sure what the `jtos_jsu_json` stuff is. Not really able to help you out here, unless it uses JSMN. Then, you'd have to share code of that library.
