### ISSUE TITLE
[jsmnerr_t] Enum size on embedded devices.

### ISSUE THREAD

**Issue by JeremieRapin** [zserge/jsmn#57]
With a STM32F1xx and the GCC compiler, the enum size is forced on 1 byte.
With large JSONs, the number of tokens can't be greater than 127, otherwise the result is negative.
One solution is to force the enum on 2 bytes like this:

``` c
typedef enum {
    /* Not enough tokens were provided */
    JSMN_ERROR_NOMEM = 0xFFFF,
    /* Invalid character inside JSON string */
    JSMN_ERROR_INVAL = 0xFFFE,
    /* The string is not a full JSON packet, more bytes expected */
    JSMN_ERROR_PART = 0xFFFD,
} jsmnerr_t;
```

2 bytes means 32,767 tokens, enough on the most cases?

**Comment by f2404** [comment]
I don't understand... how is the number of tokens correlated with the error values?

**Comment by zserge** [comment]
I agree, and current `tip` version returns `int`, not `jsmnerr_t` (https://github.com/zserge/jsmn/commit/d0664f9a2ee942e0edaa255309f67b3f77e04b50)

**Comment by JeremieRapin** [comment]
The `jsmn_parse` prototype function returns `jsmnerr_t`.
But the function returns in case of success `count`(int). If `count` is greater than 127 (in my case), then the value returned has a negative value. 
A cast occurs between `count` (int) and `jsmnerr_t` (int8_t).

tip stands for?

**Comment by MacGritsch** [comment]
it was changed 17 days before - now it is int.

**Comment by JeremieRapin** [comment]
My apologies, indeed, it was fixed. Thanks for the help and the reactivity. Issue can be closed.

**Comment by f2404** [comment]
@JeremieRapin you should be able to close the issue.
