### ISSUE TITLE
Website example uses missing type jsmnerr_t

### ISSUE THREAD

**Issue by monkbroc** [zserge/jsmn#64]
http://zserge.com/jsmn.html has this example

```
jsmntok_t tokens[256];
const char *js;
jsmnerr_t r;

js = ...;
r = jsmn_parse(&parser, js, tokens, 256);
```

`jsmnerr_t` is not a type in `jsmn.h`. `jsmn_parse` actually returns `int`.

In addition `jsmn_parse` needs the length of `js` as a 3rd argument.

Could you please update the website to reflect this?

Thanks for the neat library :+1:

**Comment by zserge** [comment]
Thanks, fixed!
