### ISSUE TITLE
minor documentation issues

### ISSUE THREAD

**Issue by xorbug** [zserge/jsmn#67]
Hi,
in the README, section 'API', jsmn_parse() takes 4 arguments, but actually 5 are needed (the undocumented one should be of size_t type, just after js, which i guess is something like strlen(js), isn't it?)
The same for the doc on the project website zserge.com/jsmn.html, which also points to bitbucket instead of github, including the command to clone the repo.

Thanks.

**Comment by zserge** [comment]
Correct, fixed. Thanks!
