### ISSUE TITLE
error compiling on Keil

### ISSUE THREAD

**Issue by gloffreda** [zserge/jsmn#73]
assembling libjsmn.a...
lib\libjsmn.a(1): error: A1167E: Invalid line start 
\20           1457567232  501   20    100644  68        `(1): error: A1163E: Unknown opcode SORTED , expecting opcode or Macro
\20           1457567232  501   20    100644  68`(2): error: A1167E: Invalid line start 
\20           1457567232  501   20    100644  68        `(3): error: A1167E: Invalid line start 
\20           1457567232  501   20    100644  68`(4): error: A1167E: Invalid line start 
\20           1457567232  501   20    100644  68        `(6): error: A1167E: Invalid line start 
\20           1457567232  501   20    100644  68`(7): error: A1167E: Invalid line start 
\20           1457567232  501   20    100644  68        `(8): warning: A1313W: Missing END directive at end of file

**Comment by zzz-13-zzz** [comment]
OMG! Don't you see that you're trying to assemble lib file with Keil assembler? If you want to use it with Keil just add two files: jsmn.c and jsmn.h to your Keil project. That's it. ... Just curious, how did you get that file: libjsmn.a ?

**Comment by cebtenzzre** [comment]
What even is this?  Why is this issue still open??
