### ISSUE TITLE
Does this library fully support unicode(UTF-8) ?

### ISSUE THREAD

**Issue by ghost** [zserge/jsmn#74]
Hello,
I'm looking for a good json library for C like yours.
jsmn looks almost perfect for me but one thing.

Looking into the benchmark link in your page (http://lionet.livejournal.com/118853.html),
Look like this library is not able to handle utf-8 characters.
Do you have any plans to make it work for utf-8?

Thanks!

**Comment by MacGritsch** [comment]
there are a few other threads regarding utf8.
it is not supported by jsmn but can be added easily.

**Comment by ghost** [comment]
Could you help me where to find that threads?

**Comment by MacGritsch** [comment]
https://github.com/zserge/jsmn/issues/48

**Comment by ghost** [comment]
Thanks..
